[project]
name = "filter_csv_generic"
version = "0.2.0"

[tool.poetry]
name = "filter_csv_generic"
version = "0.2.0"
description = ""
authors = ["Thomas <oeth@aarhus.dk>"]
readme = "README.md"
include = ["pyproject.toml"]
# packages = [{include = "filter_csv_generic"}]

[tool.poetry.dependencies]
python = ">=3.8,<3.12"
pyinstaller = "^5.10.0"

[tool.poetry.scripts]
backupsearch = "filter_csv_generic.main:main"

[tool.poetry.group.dev.dependencies]
pytest = "*"
pytest-cov = "*"
black = "*"
flake8 = "*"
mypy = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.black]
line-length = 100
